### ISSUE TITLE
Sessions timeout after ~24hrs

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#558]
It's becoming common to see the following error after switching to refresh tokens:

```
Error: Missing Refresh Token (audience: 'https://api.seasketch.org', scope: 'openid profile email offline_access')
    at new OAuthError (errors.tsx:8:1)
    at utils.tsx:15:1
    at auth0-provider.tsx:206:1
    at step (version.ts:1:1)
    at Object.throw (version.ts:1:1)
    at rejected (version.ts:1:1)

```

Always occurs after a weekend coming back into the office, and seems to happen after ~24hrs. Both localhost and production.

**Comment by underbluewaters** [comment]
Seems that auth0 config changes have fixed this.
